"""chats and messages

Revision ID: a3861c56151b
Revises: 973d8c5aba7d
Create Date: 2023-12-09 10:19:28.570570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3861c56151b'
down_revision = '973d8c5aba7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatMessages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('message_id', 'chat_id')
    )
    op.create_table('userChats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermarkets',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('market_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name='usermarkets_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='usermarkets_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'market_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('userorders',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='userorders_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='userorders_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('productorder',
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='productorder_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='productorder_ibfk_2'),
    sa.PrimaryKeyConstraint('order_id', 'product_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('userChats')
    op.drop_table('chatMessages')
    op.drop_table('userOrders')
    op.drop_table('userMarkets')
    op.drop_table('chats')
    op.drop_table('productOrder')
    op.drop_table('messages')
    # ### end Alembic commands ###
